name: CI Workflow

on:
    push:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
            - name: Setup Docker
              uses: docker/setup-buildx-action@v4